import SwiftUI
import AppKit
import Combine

@main
struct ClipApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) private var delegate

    var body: some Scene {
        // SwiftUI requires at least one scene. The actual preferences window is
        // managed by AppDelegate.openPreferences() (NSWindow + NSHostingController).
        Settings { EmptyView() }
    }
}

@MainActor
final class AppDelegate: NSObject, NSApplicationDelegate {
    var store: HistoryStore!
    var blacklist: BlacklistService!
    var observer: PasteboardObserver!
    var hotkey: HotkeyManager!
    var statusItem: StatusItemController!
    var panelModel: PanelModel!
    var panel: PanelWindow!
    let injector = PasteInjector()
    var pruner: DispatchSourceTimer!

    // Cloud sync (T25). Engine + the two background drainer/poll tasks.
    var syncEngine: SyncEngine?
    private var pushLoopTask: Task<Void, Never>?
    private var pullLoopTask: Task<Void, Never>?

    private var onboardingWindow: NSWindow?
    private var preferencesWindow: NSWindow?
    private var cancellables: Set<AnyCancellable> = []

    func applicationDidFinishLaunching(_ note: Notification) {
        // 1. Single-instance check
        if AppDelegate.terminateIfDuplicateInstance() { return }

        // 2. Activation policy (LSUIElement-style menu bar accessory)
        NSApplication.shared.setActivationPolicy(.accessory)

        // 3. Storage
        let dbPath = Self.databasePath()
        do {
            store = try HistoryStore(path: dbPath)
        } catch {
            let alert = NSAlert()
            alert.messageText = "无法打开剪贴板数据库"
            alert.informativeText = "\(dbPath)\n\n\(error)"
            alert.alertStyle = .critical
            alert.runModal()
            NSApp.terminate(nil)
            return
        }

        // 4. Blacklist
        blacklist = BlacklistService(store: store)

        // 5. Wire PreferencesContainer so Settings views can reach live services
        PreferencesContainer.shared.blacklist = blacklist
        PreferencesContainer.shared.store = store
        PreferencesContainer.shared.dbPath = dbPath

        // 6. PasteboardObserver with closures pulling latest UserDefaults / frontmost app
        let filterBuilder: () -> PrivacyFilter = {
            let d = UserDefaults.standard
            return PrivacyFilter(
                respectConcealed:     d.object(forKey: "clip.privacy.respectConcealed")     as? Bool ?? true,
                respectTransient:     d.object(forKey: "clip.privacy.respectTransient")     as? Bool ?? true,
                respectAutoGenerated: d.object(forKey: "clip.privacy.respectAutoGenerated") as? Bool ?? true
            )
        }
        // Capture the service directly (it's Sendable / thread-safe) so the
        // observer's background-queue closure does NOT cross MainActor isolation.
        let blacklistService = blacklist!
        let blacklistBuilder: () -> Set<String> = {
            (try? blacklistService.currentSet()) ?? []
        }
        let frontmostBuilder: () -> (bundleID: String?, name: String?) = {
            let a = NSWorkspace.shared.frontmostApplication
            return (a?.bundleIdentifier, a?.localizedName)
        }
        observer = PasteboardObserver(
            source: NSPasteboardSource(),
            store: store,
            filter: filterBuilder,
            blacklist: blacklistBuilder,
            frontmost: frontmostBuilder
        )
        observer.start()

        // 7.5 Cloud sync (v3, D1+R2). Spec §4.1.
        startCloudSyncIfEnabled()
        // Notification fires on the main queue (passed below), but Swift 6's
        // strict concurrency can't see that statically — bounce through
        // MainActor.assumeIsolated to assert isolation explicitly.
        NotificationCenter.default.addObserver(
            forName: .clipCloudSyncDidEnable, object: nil, queue: .main
        ) { [weak self] _ in
            MainActor.assumeIsolated {
                guard let self else { return }
                self.startCloudSyncIfEnabled()
                // First-device backfill on cold-start of engine
                if let engine = self.syncEngine {
                    Task { try? await engine.backfill(now: Int64(Date().timeIntervalSince1970)) }
                }
            }
        }

        // 7. Hotkey
        hotkey = HotkeyManager()
        hotkey.onToggle = { [weak self] in self?.togglePanel() }
        hotkey.install()

        // 8. Panel + model wired with paste callback
        panel = PanelWindow()
        panelModel = PanelModel(store: store) { [weak self] item in
            guard let self else { return }
            switch item.kind {
            case .text:
                self.injector.paste(content: item.content) { [weak self] in
                    self?.panel.close()
                }
            case .image:
                guard let blobID = item.blobID else { self.panel.close(); return }
                // Lazy blob fetch (T25): if local bytes are empty (placeholder
                // row from a pull), await engine.fetchBlob before pasting.
                Task {
                    var bytes = (try? self.store.blob(id: blobID)) ?? Data()
                    if bytes.isEmpty, let engine = self.syncEngine {
                        bytes = (try? await engine.fetchBlob(blobID: blobID)) ?? Data()
                    }
                    await MainActor.run {
                        if !bytes.isEmpty {
                            self.injector.pasteImage(
                                bytes: bytes,
                                mimeType: item.mimeType ?? "image/png"
                            ) { self.panel.close() }
                        } else {
                            self.panel.close()
                        }
                    }
                }
            }
        }
        panel.setRoot(PanelView(model: panelModel))

        // Drive the global PreviewWindow off the model's previewItem. Sink
        // outside the panel so the preview can render larger than the panel
        // itself and float at modalPanel level above it.
        panelModel.$previewItem
            .receive(on: RunLoop.main)
            .sink { [weak self] item in
                guard let self else { return }
                if let item {
                    PreviewWindow.shared.show(item: item, model: self.panelModel) {
                        // PreviewWindow's own ⎵ / esc dismissed it; clear the
                        // model so the published state matches.
                        self.panelModel.previewItem = nil
                    }
                } else {
                    PreviewWindow.shared.hide()
                }
            }
            .store(in: &cancellables)

        // Wire the panel's local-monitor key handlers into the model.
        let model = panelModel!
        let panelRef = panel!
        panel.keyHandlers = PanelWindow.KeyHandlers(
            onUp:    { model.moveSelection(by: -1) },
            onDown:  { model.moveSelection(by: 1) },
            onEnter: { model.paste() },
            onEscape: { panelRef.close() },
            onPin:    { Task { await model.togglePinSelected() } },
            onDelete: { [weak self] in self?.deleteSelectedFromPanel() },
            onIndex:  { n in model.selectIndex(n) },
            // ⌘F is handled by a SwiftUI keyboardShortcut button inside
            // PanelView (it needs @FocusState access). The window monitor
            // never sees ⌘F because PanelWindow.handleKeyDown returns the
            // event for ⌘F to flow into SwiftUI. (Currently we DO consume
            // ⌘F in handleKeyDown — switch to no-op there if you want the
            // SwiftUI button to take over.)
            onFocusSearch: { /* no-op; SwiftUI button handles it */ },
            onPrevPage: { model.prevPage() },
            onNextPage: { model.nextPage() },
            onPreview:  { model.togglePreview() },
            onSwitchTab: { n in
                let tabs: [ContentFilter] = [.all, .text, .image]
                guard tabs.indices.contains(n - 1) else { return }
                model.contentFilter = tabs[n - 1]
            }
        )

        // 9. Status item
        statusItem = StatusItemController()
        statusItem.onOpenPanel = { [weak self] in self?.togglePanel() }
        statusItem.onTogglePause = { [weak self] in self?.togglePause() }
        statusItem.onOpenPreferences = { [weak self] in self?.openPreferences() }

        // 10. Pruner timer
        startPruner()

        // 11. Onboarding (first run, or Accessibility-only on re-launch)
        showOnboardingIfNeeded()
    }

    private func togglePanel() {
        if panel.isVisible {
            panel.close()
        } else {
            panelModel.prepareForShow()
            panel.showAtCursor()
        }
    }

    /// Wraps `PanelModel.deleteSelected` with the NSAlert pinned-confirmation
    /// dialog. Called from `PanelWindow`'s key monitor when user hits ⌘D / ⌫.
    private func deleteSelectedFromPanel() {
        let model = panelModel!
        let panelRef = panel!
        Task { @MainActor in
            await model.deleteSelected {
                await PanelDeleteConfirm.confirm(
                    window: panelRef,
                    content: model.selectedItem()?.content ?? ""
                )
            }
        }
    }

    private func togglePause() {
        statusItem.isPaused.toggle()
        if statusItem.isPaused {
            observer.pause()
        } else {
            observer.resume()
        }
    }

    /// Lazily create and present the preferences window. We don't use SwiftUI's
    /// `Settings { ... }` scene because in LSUIElement (accessory) apps the
    /// `showSettingsWindow:` selector has no responder — there's no app menu bar
    /// for SwiftUI to wire it into — so the menu item silently does nothing.
    /// Manage an NSWindow ourselves and host the SwiftUI view.
    private func openPreferences() {
        if let w = preferencesWindow {
            NSApp.activate(ignoringOtherApps: true)
            w.makeKeyAndOrderFront(nil)
            return
        }
        let host = NSHostingController(rootView: PreferencesWindow())
        let w = NSWindow(contentViewController: host)
        w.title = "Clip 偏好设置"
        w.styleMask = [.titled, .closable, .miniaturizable]
        w.isReleasedWhenClosed = false
        w.center()
        preferencesWindow = w
        NSApp.activate(ignoringOtherApps: true)
        w.makeKeyAndOrderFront(nil)
    }

    static func databasePath() -> String {
        let dir = NSString(string: "~/Library/Application Support/clip").expandingTildeInPath
        try? FileManager.default.createDirectory(
            atPath: dir,
            withIntermediateDirectories: true
        )
        return (dir as NSString).appendingPathComponent("history.sqlite")
    }
}

// MARK: - Single-instance guard
extension AppDelegate {
    /// Returns `true` if another instance is already running and the current
    /// process has been told to terminate. Caller should `return` immediately.
    static func terminateIfDuplicateInstance() -> Bool {
        let mine = Bundle.main.bundleIdentifier ?? "com.zyw.clip"
        let myPID = ProcessInfo.processInfo.processIdentifier
        let others = NSRunningApplication
            .runningApplications(withBundleIdentifier: mine)
            .filter { $0.processIdentifier != myPID }
        guard let other = others.first else { return false }
        other.activate()
        NSApp.terminate(nil)
        return true
    }
}

// MARK: - Pruner timer
extension AppDelegate {
    func startPruner() {
        // Run on the main queue. Pruning is a sub-millisecond SQLite DELETE on
        // a 500-row table firing every 60s — no UI impact. Running on main
        // avoids Swift 6's runtime actor-isolation check (the timer closure
        // is implicitly @MainActor since startPruner() is, and dispatching to
        // a background queue would trip dispatch_assert_queue_fail / SIGTRAP).
        let store = self.store!
        let t = DispatchSource.makeTimerSource(queue: .main)
        t.schedule(
            deadline: .now() + 60,
            repeating: 60,
            leeway: .seconds(5)
        )
        t.setEventHandler {
            let cfg = RetentionConfig.current()
            let now = Int64(Date().timeIntervalSince1970)
            try? store.prune(
                now: now,
                maxText: cfg.maxItems,
                maxImage: cfg.maxImageItems,
                maxAgeSeconds: Int64(cfg.maxDays) * 86_400
            )
        }
        t.resume()
        self.pruner = t
    }
}

// MARK: - Onboarding-on-first-run wiring
extension AppDelegate {
    func showOnboardingIfNeeded() {
        let onboarded = UserDefaults.standard.bool(forKey: "clip.onboarded")
        let trusted = AccessibilityCheck.isTrusted(prompt: false)

        // Already onboarded AND Accessibility still granted: nothing to do.
        if onboarded && trusted { return }

        // Reuse window if already visible.
        if let w = onboardingWindow, w.isVisible {
            w.makeKeyAndOrderFront(nil)
            NSApp.activate(ignoringOtherApps: true)
            return
        }

        let accessibilityOnly = onboarded && !trusted
        let view = OnboardingWindow(accessibilityOnly: accessibilityOnly) { [weak self] in
            self?.onboardingWindow?.close()
            self?.onboardingWindow = nil
        }
        let host = NSHostingController(rootView: view)
        let w = NSWindow(contentViewController: host)
        w.title = "欢迎使用 Clip"
        w.styleMask = [.titled, .closable]
        w.isReleasedWhenClosed = false
        w.center()
        w.level = .floating
        onboardingWindow = w

        NSApp.activate(ignoringOtherApps: true)
        w.makeKeyAndOrderFront(nil)
    }
}

// MARK: - Cloud sync wire-in (Task 25)
extension AppDelegate {
    func startCloudSyncIfEnabled() {
        let settings = PreferencesContainer.shared.syncSettings
        guard settings.enabled,
              let endpoint = settings.r2Endpoint.flatMap(URL.init),
              let bucket = settings.r2Bucket,
              let r2AK = settings.r2AccessKeyID,
              let r2Secret = (try? KeychainStore(service: "com.zyw.clip.cloud-r2-secret-v1")
                              .read(account: "current")).flatMap({ String(data: $0, encoding: .utf8) }),
              let d1AccountID = settings.d1AccountID,
              let d1DatabaseID = settings.d1DatabaseID,
              let d1Token = (try? KeychainStore(service: "com.zyw.clip.cloud-d1-token-v1")
                             .read(account: "current")).flatMap({ String(data: $0, encoding: .utf8) }),
              let masterKey = try? KeychainStore(service: "com.zyw.clip.cloud-master-v1")
                                  .read(account: "current")
        else { return }

        let crypto = CryptoBox(masterKey: masterKey)
        let blobs = R2BlobBackend(endpoint: endpoint, bucket: bucket,
                                  accessKeyID: r2AK, secretAccessKey: r2Secret)
        let ds = D1Backend(accountID: d1AccountID, databaseID: d1DatabaseID,
                           apiToken: d1Token)

        // Spec §5.2 / fix E — verify remote schema on every cold start. Don't
        // start the engine if remote is newer (refuse to mutate data we don't
        // understand). Failure is surfaced via NSAlert; sync stays disabled
        // for this session.
        Task {
            do {
                try await SyncEngine.verifyRemoteSchema(dataSource: ds)
                await MainActor.run { self.startCloudSyncEngineCore(
                    ds: ds, blobs: blobs, crypto: crypto, masterKey: masterKey) }
            } catch let SyncError.remoteSchemaNewer(remote, local) {
                await MainActor.run {
                    let alert = NSAlert()
                    alert.messageText = "需要升级 Clip"
                    alert.informativeText = "另一台 Mac 装了更新版本的 Clip (云端 schema v\(remote);本机 v\(local))。请升级本机后重启同步。"
                    alert.alertStyle = .warning
                    alert.runModal()
                }
            } catch {
                NSLog("[clip] verifyRemoteSchema failed: \(error)")
            }
        }
    }

    /// Caller has verified schema; actually wire the engine + start loops.
    private func startCloudSyncEngineCore(ds: CloudSyncDataSource,
                                          blobs: CloudSyncBlobStore,
                                          crypto: CryptoBox,
                                          masterKey: Data) {
        let state = SyncStateStore(store: store)
        let deviceID = (try? state.get("device_id")) ?? UUID().uuidString.lowercased()
        try? state.set("device_id", deviceID)

        let engine = SyncEngine(store: store, dataSource: ds, blobStore: blobs,
                                crypto: crypto, deviceID: deviceID, state: state)
        self.syncEngine = engine

        // Wire HistoryStore.onChange → engine.enqueue. The closure captures the
        // store directly (Sendable) rather than `self` so it can run on the
        // mutation thread without crossing MainActor isolation.
        let storeRef = self.store!
        store.onChange = { [weak engine] change in
            guard let engine else { return }
            let now = Int64(Date().timeIntervalSince1970)
            Task {
                switch change {
                case .inserted(let id):
                    try? await engine.enqueueClipPush(itemID: id, at: now)
                    if let item = try? storeRef.itemByID(id),
                       let blobID = item.blobID {
                        try? await engine.enqueueBlobPush(blobID: blobID, at: now)
                    }
                case .deleted(_, let hash):
                    try? await engine.excludeItemByHash(contentHash: hash, at: now)
                case .pinToggled(let id):
                    try? await engine.enqueueClipPush(itemID: id, at: now)
                case .excludedToggled:
                    break  // handled by engine.excludeItem directly
                }
            }
        }

        // Wire panel ⌘N (PanelModel.onExclude — T23)
        panelModel.onExclude = { [weak engine] id in
            guard let engine else { return }
            let now = Int64(Date().timeIntervalSince1970)
            Task { try? await engine.excludeItem(id: id, at: now) }
        }

        // Background push drainer + 30s pull tick. Capture the engine weakly
        // so if AppDelegate releases it the loops self-terminate.
        pushLoopTask = Task { [weak engine] in
            while !Task.isCancelled, let engine {
                let did = (try? await engine.pushOnce(now: Int64(Date().timeIntervalSince1970))) ?? false
                if !did { try? await Task.sleep(nanoseconds: 1_000_000_000) }
            }
        }
        pullLoopTask = Task { [weak engine] in
            while !Task.isCancelled, let engine {
                _ = try? await engine.pullOnce(now: Int64(Date().timeIntervalSince1970))
                try? await Task.sleep(nanoseconds: 30_000_000_000)
            }
        }
    }
}
