import SwiftUI
import AppKit

@main
struct ClipApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) private var delegate

    var body: some Scene {
        Settings { PreferencesWindow() }
    }
}

@MainActor
final class AppDelegate: NSObject, NSApplicationDelegate {
    var store: HistoryStore!
    var blacklist: BlacklistService!
    var observer: PasteboardObserver!
    var hotkey: HotkeyManager!
    var statusItem: StatusItemController!
    var panelModel: PanelModel!
    var panel: PanelWindow!
    let injector = PasteInjector()
    var pruner: DispatchSourceTimer!

    private var onboardingWindow: NSWindow?

    func applicationDidFinishLaunching(_ note: Notification) {
        // 1. Single-instance check
        if AppDelegate.terminateIfDuplicateInstance() { return }

        // 2. Activation policy (LSUIElement-style menu bar accessory)
        NSApplication.shared.setActivationPolicy(.accessory)

        // 3. Storage
        let dbPath = Self.databasePath()
        do {
            store = try HistoryStore(path: dbPath)
        } catch {
            let alert = NSAlert()
            alert.messageText = "无法打开剪贴板数据库"
            alert.informativeText = "\(dbPath)\n\n\(error)"
            alert.alertStyle = .critical
            alert.runModal()
            NSApp.terminate(nil)
            return
        }

        // 4. Blacklist
        blacklist = BlacklistService(store: store)

        // 5. Wire PreferencesContainer so Settings views can reach live services
        PreferencesContainer.shared.blacklist = blacklist
        PreferencesContainer.shared.store = store
        PreferencesContainer.shared.dbPath = dbPath

        // 6. PasteboardObserver with closures pulling latest UserDefaults / frontmost app
        let filterBuilder: () -> PrivacyFilter = {
            let d = UserDefaults.standard
            return PrivacyFilter(
                respectConcealed:     d.object(forKey: "clip.privacy.respectConcealed")     as? Bool ?? true,
                respectTransient:     d.object(forKey: "clip.privacy.respectTransient")     as? Bool ?? true,
                respectAutoGenerated: d.object(forKey: "clip.privacy.respectAutoGenerated") as? Bool ?? true
            )
        }
        let blacklistBuilder: () -> Set<String> = { [weak self] in
            (try? self?.blacklist.currentSet()) ?? []
        }
        let frontmostBuilder: () -> (bundleID: String?, name: String?) = {
            let a = NSWorkspace.shared.frontmostApplication
            return (a?.bundleIdentifier, a?.localizedName)
        }
        observer = PasteboardObserver(
            source: NSPasteboardSource(),
            store: store,
            filter: filterBuilder,
            blacklist: blacklistBuilder,
            frontmost: frontmostBuilder
        )
        observer.start()

        // 7. Hotkey
        hotkey = HotkeyManager()
        hotkey.onToggle = { [weak self] in self?.togglePanel() }
        hotkey.install()

        // 8. Panel + model wired with paste callback
        panel = PanelWindow()
        panelModel = PanelModel(store: store) { [weak self] item in
            guard let self else { return }
            self.injector.paste(content: item.content) { [weak self] in
                self?.panel.close()
            }
        }
        panel.setRoot(PanelView(model: panelModel))

        // 9. Status item
        statusItem = StatusItemController()
        statusItem.onOpenPanel = { [weak self] in self?.togglePanel() }
        statusItem.onTogglePause = { [weak self] in self?.togglePause() }
        statusItem.onOpenPreferences = {
            NSApp.sendAction(Selector(("showSettingsWindow:")), to: nil, from: nil)
        }

        // 10. Pruner timer
        startPruner()

        // 11. Onboarding (first run, or Accessibility-only on re-launch)
        showOnboardingIfNeeded()
    }

    private func togglePanel() {
        if panel.isVisible {
            panel.close()
        } else {
            panelModel.prepareForShow()
            panel.showAtCursor()
        }
    }

    private func togglePause() {
        statusItem.isPaused.toggle()
        if statusItem.isPaused {
            observer.pause()
        } else {
            observer.resume()
        }
    }

    static func databasePath() -> String {
        let dir = NSString(string: "~/Library/Application Support/clip").expandingTildeInPath
        try? FileManager.default.createDirectory(
            atPath: dir,
            withIntermediateDirectories: true
        )
        return (dir as NSString).appendingPathComponent("history.sqlite")
    }
}

// MARK: - Task 48: Single-instance guard
extension AppDelegate {
    /// Returns `true` if another instance is already running and the current
    /// process has been told to terminate. Caller should `return` immediately.
    static func terminateIfDuplicateInstance() -> Bool {
        let mine = Bundle.main.bundleIdentifier ?? "com.zyw.clip"
        let myPID = ProcessInfo.processInfo.processIdentifier
        let others = NSRunningApplication
            .runningApplications(withBundleIdentifier: mine)
            .filter { $0.processIdentifier != myPID }
        guard let other = others.first else { return false }
        other.activate()
        NSApp.terminate(nil)
        return true
    }
}

// MARK: - Task 49: Pruner timer
extension AppDelegate {
    func startPruner() {
        let t = DispatchSource.makeTimerSource(queue: .global(qos: .utility))
        t.schedule(
            deadline: .now() + 60,
            repeating: 60,
            leeway: .seconds(5)
        )
        t.setEventHandler { [weak self] in
            guard let self else { return }
            let cfg = RetentionConfig.current()
            let now = Int64(Date().timeIntervalSince1970)
            do {
                try self.store.prune(
                    now: now,
                    maxCount: cfg.maxItems,
                    maxAgeSeconds: Int64(cfg.maxDays) * 86_400
                )
            } catch {
                // Prune is best-effort; swallow and let the next tick retry.
            }
        }
        t.resume()
        self.pruner = t
    }
}

// MARK: - Task 50: Onboarding-on-first-run wiring
extension AppDelegate {
    func showOnboardingIfNeeded() {
        let onboarded = UserDefaults.standard.bool(forKey: "clip.onboarded")
        let trusted = AccessibilityCheck.isTrusted(prompt: false)

        // Already onboarded AND Accessibility still granted: nothing to do.
        if onboarded && trusted { return }

        // Reuse window if already visible.
        if let w = onboardingWindow, w.isVisible {
            w.makeKeyAndOrderFront(nil)
            NSApp.activate(ignoringOtherApps: true)
            return
        }

        let accessibilityOnly = onboarded && !trusted
        let view = OnboardingWindow(accessibilityOnly: accessibilityOnly) { [weak self] in
            self?.onboardingWindow?.close()
            self?.onboardingWindow = nil
        }
        let host = NSHostingController(rootView: view)
        let w = NSWindow(contentViewController: host)
        w.title = "欢迎使用 Clip"
        w.styleMask = [.titled, .closable]
        w.isReleasedWhenClosed = false
        w.center()
        w.level = .floating
        onboardingWindow = w

        NSApp.setActivationPolicy(.regular)  // Temporarily show in Dock so the window grabs focus.
        NSApp.activate(ignoringOtherApps: true)
        w.makeKeyAndOrderFront(nil)

        // Restore .accessory once the onboarding window closes.
        NotificationCenter.default.addObserver(
            forName: NSWindow.willCloseNotification,
            object: w,
            queue: .main
        ) { _ in
            Task { @MainActor in
                NSApp.setActivationPolicy(.accessory)
            }
        }
    }
}
