import AppKit

struct PrivacyFilter {
    var respectConcealed = true
    var respectTransient = true
    var respectAutoGenerated = true

    static let concealedUTI = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientUTI = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenUTI   = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    // Note: internal-paste check runs FIRST so we never re-ingest our own paste.
    static let internalUTI  = NSPasteboard.PasteboardType("com.zyw.clip.internal-paste")

    /// Returns reason string if filtered, nil if accepted.
    func reasonToSkip(types: Set<NSPasteboard.PasteboardType>, content: String,
                      sourceBundleID: String?, blacklist: Set<String>) -> String? {
        if types.contains(Self.internalUTI) { return "internal-paste" }
        if respectConcealed && types.contains(Self.concealedUTI) { return "concealed" }
        if respectTransient && types.contains(Self.transientUTI) { return "transient" }
        if respectAutoGenerated && types.contains(Self.autoGenUTI) { return "auto-generated" }
        if content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return "empty" }
        if let bid = sourceBundleID, blacklist.contains(bid) { return "blacklisted" }
        return nil
    }
}
