import SwiftUI
import AppKit
import UniformTypeIdentifiers

/// Privacy preferences:
/// - Three @AppStorage toggles for the org.nspasteboard markers.
/// - A blacklist editor backed by BlacklistService. "+" opens an NSOpenPanel
///   filtered to applications under /Applications; OK extracts bundleIdentifier
///   and a human-readable display name from the chosen .app bundle.
///
/// The service is injected so the same instance the observer uses also
/// drives this UI. AppDelegate stuffs it into PreferencesContainer at launch.
struct PrivacyView: View {
    @AppStorage("clip.privacy.respectConcealed")     private var respectConcealed: Bool = true
    @AppStorage("clip.privacy.respectTransient")     private var respectTransient: Bool = true
    @AppStorage("clip.privacy.respectAutoGenerated") private var respectAutoGenerated: Bool = true

    @State private var entries: [(bundleID: String, displayName: String)] = []
    @State private var selection: String?
    @State private var errorText: String?

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            GroupBox("敏感内容标记") {
                VStack(alignment: .leading) {
                    Toggle("尊重 Concealed（密码管理器等）",  isOn: $respectConcealed)
                    Toggle("尊重 Transient（临时复制）",      isOn: $respectTransient)
                    Toggle("尊重 AutoGenerated（自动生成）",  isOn: $respectAutoGenerated)
                }
                .padding(8)
            }

            GroupBox("应用黑名单") {
                VStack(alignment: .leading, spacing: 6) {
                    List(selection: $selection) {
                        ForEach(entries, id: \.bundleID) { e in
                            HStack {
                                Text(e.displayName)
                                Spacer()
                                Text(e.bundleID)
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                            .tag(e.bundleID)
                        }
                    }
                    .frame(minHeight: 120)

                    HStack {
                        Button {
                            addViaOpenPanel()
                        } label: { Image(systemName: "plus") }

                        Button {
                            removeSelected()
                        } label: { Image(systemName: "minus") }
                            .disabled(selection == nil)
                    }

                    if let errorText {
                        Text(errorText).font(.caption).foregroundStyle(.red)
                    }
                }
                .padding(8)
            }
        }
        .padding(20)
        .onAppear { reload() }
    }

    private var blacklist: BlacklistService? {
        PreferencesContainer.shared.blacklist
    }

    private func reload() {
        do {
            entries = try blacklist?.list() ?? []
            errorText = nil
        } catch {
            entries = []
            errorText = "读取黑名单失败：\(error.localizedDescription)"
        }
    }

    private func addViaOpenPanel() {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.application]
        panel.allowsMultipleSelection = false
        panel.canChooseDirectories = false
        panel.canChooseFiles = true
        panel.directoryURL = URL(fileURLWithPath: "/Applications")
        panel.prompt = "添加"
        panel.message = "选择不希望被采集剪贴板内容的应用"

        guard panel.runModal() == .OK, let url = panel.url else { return }
        guard let bundle = Bundle(url: url),
              let bid = bundle.bundleIdentifier
        else {
            errorText = "无法读取所选应用的 bundle identifier。"
            return
        }
        let info = bundle.infoDictionary
        let name = (info?["CFBundleDisplayName"] as? String)
                ?? (info?["CFBundleName"] as? String)
                ?? url.deletingPathExtension().lastPathComponent

        do {
            try blacklist?.add(bundleID: bid, displayName: name)
            reload()
        } catch {
            errorText = "添加失败：\(error.localizedDescription)"
        }
    }

    private func removeSelected() {
        guard let bid = selection else { return }
        do {
            try blacklist?.remove(bundleID: bid)
            selection = nil
            reload()
        } catch {
            errorText = "移除失败：\(error.localizedDescription)"
        }
    }
}

/// Lightweight injection seam: AppDelegate sets `.shared.blacklist` /
/// `.shared.dbPath` / `.shared.store` on launch so the SwiftUI Settings views
/// (which can't take constructor args) can reach the live services.
final class PreferencesContainer: @unchecked Sendable {
    static let shared = PreferencesContainer()
    var blacklist: BlacklistService?
    var store: HistoryStore?
    var dbPath: String?
    var syncSettings: SyncSettings = SyncSettings()
    private init() {}
}
