import XCTest
import AppKit
@testable import Clip

final class PrivacyFilterTests: XCTestCase {
    func testAcceptsPlainTextWithNoMarkers() {
        let f = PrivacyFilter()
        let reason = f.reasonToSkip(
            types: [.string],
            content: "hello world",
            sourceBundleID: "com.apple.Safari",
            blacklist: []
        )
        XCTAssertNil(reason)
    }

    func testInternalPasteUTIIsSkipped() {
        let f = PrivacyFilter()
        let reason = f.reasonToSkip(
            types: [.string, PrivacyFilter.internalUTI],
            content: "anything",
            sourceBundleID: "com.zyw.clip",
            blacklist: []
        )
        XCTAssertEqual(reason, "internal-paste")
    }

    func testConcealedReason() {
        let f = PrivacyFilter()
        let r = f.reasonToSkip(types: [.string, PrivacyFilter.concealedUTI],
                               content: "secret", sourceBundleID: nil, blacklist: [])
        XCTAssertEqual(r, "concealed")
    }

    func testTransientReason() {
        let f = PrivacyFilter()
        let r = f.reasonToSkip(types: [.string, PrivacyFilter.transientUTI],
                               content: "tmp", sourceBundleID: nil, blacklist: [])
        XCTAssertEqual(r, "transient")
    }

    func testAutoGeneratedReason() {
        let f = PrivacyFilter()
        let r = f.reasonToSkip(types: [.string, PrivacyFilter.autoGenUTI],
                               content: "gen", sourceBundleID: nil, blacklist: [])
        XCTAssertEqual(r, "auto-generated")
    }

    func testEmptyContentReason() {
        let f = PrivacyFilter()
        let r = f.reasonToSkip(types: [.string], content: "   \n\t  ",
                               sourceBundleID: "com.apple.Notes", blacklist: [])
        XCTAssertEqual(r, "empty")
    }

    func testBlacklistedReason() {
        let f = PrivacyFilter()
        let r = f.reasonToSkip(types: [.string], content: "ok",
                               sourceBundleID: "com.agilebits.onepassword7",
                               blacklist: ["com.agilebits.onepassword7"])
        XCTAssertEqual(r, "blacklisted")
    }

    func testBlacklistMissBundleIDIsAccepted() {
        let f = PrivacyFilter()
        let r = f.reasonToSkip(types: [.string], content: "ok",
                               sourceBundleID: nil,
                               blacklist: ["com.agilebits.onepassword7"])
        XCTAssertNil(r)
    }
}
